# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

create <- function() {
    .Call(`_iptree_create`)
}

insert <- function(t, keys, values) {
    invisible(.Call(`_iptree_insert`, t, keys, values))
}

match_str <- function(t, k) {
    .Call(`_iptree_match_str`, t, k)
}

